language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_script:
  - npm install -g polymer-cli
cache: yarn
script:
  - xvfb-run npm test
